[target.x86_64-unknown-linux-musl]
pre-build = ["""
PROTOC_VERSION=29.3 && \
curl -sSLO https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip && \
unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local bin/protoc && \
rm protoc-${PROTOC_VERSION}-linux-x86_64.zip
"""]

[target.aarch64-unknown-linux-musl]
pre-build = ["""
PROTOC_VERSION=29.3 && \
curl -sSLO https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip && \
unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local bin/protoc && \
rm protoc-${PROTOC_VERSION}-linux-x86_64.zip
"""]

[target.x86_64-pc-windows-gnu]
pre-build = ["""
PROTOC_VERSION=29.3 && \
curl -sSLO https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip && \
unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local bin/protoc && \
rm protoc-${PROTOC_VERSION}-linux-x86_64.zip
"""]
