// Auto-generated by crap-cms. Do not edit.

package types

// Articles represents a articles document.
type Articles struct {
	ID        string  `json:"id"`
	Title     string `json:"title"`
	Slug      string `json:"slug"`
	Summary   *string `json:"summary,omitempty"`
	Body      *string `json:"body,omitempty"`
	Category  *string `json:"category,omitempty"`
	Author    *string `json:"author,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// Media represents a media document.
type Media struct {
	ID        string  `json:"id"`
	Filename  string `json:"filename"`
	MimeType  *string `json:"mime_type,omitempty"`
	Filesize  *float64 `json:"filesize,omitempty"`
	Width     *float64 `json:"width,omitempty"`
	Height    *float64 `json:"height,omitempty"`
	Url       *string `json:"url,omitempty"`
	ThumbnailUrl *string `json:"thumbnail_url,omitempty"`
	ThumbnailWidth *float64 `json:"thumbnail_width,omitempty"`
	ThumbnailHeight *float64 `json:"thumbnail_height,omitempty"`
	ThumbnailWebpUrl *string `json:"thumbnail_webp_url,omitempty"`
	ThumbnailAvifUrl *string `json:"thumbnail_avif_url,omitempty"`
	CardUrl   *string `json:"card_url,omitempty"`
	CardWidth *float64 `json:"card_width,omitempty"`
	CardHeight *float64 `json:"card_height,omitempty"`
	CardWebpUrl *string `json:"card_webp_url,omitempty"`
	CardAvifUrl *string `json:"card_avif_url,omitempty"`
	Alt       *string `json:"alt,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// Pages represents a pages document.
type Pages struct {
	ID        string  `json:"id"`
	Title     string `json:"title"`
	Slug      string `json:"slug"`
	Published bool `json:"published,omitempty"`
	Seo       map[string]interface{} `json:"seo,omitempty"`
	HeroImage *string `json:"hero_image,omitempty"`
	Content   []map[string]interface{} `json:"content,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// PostsSlides represents a row in the slides array field.
type PostsSlides struct {
	Title     string `json:"title"`
	ImageUrl  *string `json:"image_url,omitempty"`
	Caption   *string `json:"caption,omitempty"`
}

// Posts represents a posts document.
type Posts struct {
	ID        string  `json:"id"`
	Title     string `json:"title"`
	Slug      string `json:"slug"`
	Status    string `json:"status"`
	Content   *string `json:"content,omitempty"`
	Tags      []string `json:"tags,omitempty"`
	Slides    []PostsSlides `json:"slides,omitempty"`
	FeaturedImage *string `json:"featured_image,omitempty"`
	Author    *string `json:"author,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// Tags represents a tags document.
type Tags struct {
	ID        string  `json:"id"`
	Name      string `json:"name"`
	Color     *string `json:"color,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// Users represents a users document.
type Users struct {
	ID        string  `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	Role      string `json:"role"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// SiteSettings represents the site_settings global.
type SiteSettings struct {
	ID        string  `json:"id"`
	SiteName  string `json:"site_name"`
	Tagline   *string `json:"tagline,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

