-- Auto-generated by crap-cms. Do not edit.

---@class crap.data.Categories
---@field title string
---@field slug string
---@field description? string
---@field seo? table

---@class crap.doc.Categories
---@field id string
---@field title string
---@field slug string
---@field description? string
---@field seo? table
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Categories
---@field collection "categories"
---@field operation "create" | "update"
---@field data crap.data.Categories

---@class crap.find_result.Categories
---@field documents crap.doc.Categories[]
---@field total integer

---@alias crap.hook_fn.Categories fun(ctx: crap.hook.Categories): crap.hook.Categories

---@class crap.filters.Categories
---@field id? crap.FilterValue
---@field title? crap.FilterValue
---@field slug? crap.FilterValue
---@field description? crap.FilterValue
---@field seo__meta_title? crap.FilterValue
---@field seo__meta_description? crap.FilterValue
---@field seo__no_index? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class crap.query.Categories
---@field filters? crap.filters.Categories
---@field order_by? "id"|"-id"|"title"|"-title"|"slug"|"-slug"|"description"|"-description"|"seo__meta_title"|"-seo__meta_title"|"seo__meta_description"|"-seo__meta_description"|"seo__no_index"|"-seo__no_index"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.data.Media
---@field filename string
---@field mime_type? string
---@field filesize? number
---@field width? number
---@field height? number
---@field url? string
---@field thumbnail_url? string
---@field thumbnail_width? number
---@field thumbnail_height? number
---@field card_url? string
---@field card_width? number
---@field card_height? number
---@field hero_url? string
---@field hero_width? number
---@field hero_height? number
---@field alt string
---@field caption? string

---@class crap.doc.Media
---@field id string
---@field filename string
---@field mime_type? string
---@field filesize? number
---@field width? number
---@field height? number
---@field url? string
---@field thumbnail_url? string
---@field thumbnail_width? number
---@field thumbnail_height? number
---@field card_url? string
---@field card_width? number
---@field card_height? number
---@field hero_url? string
---@field hero_width? number
---@field hero_height? number
---@field alt string
---@field caption? string
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Media
---@field collection "media"
---@field operation "create" | "update"
---@field data crap.data.Media

---@class crap.find_result.Media
---@field documents crap.doc.Media[]
---@field total integer

---@alias crap.hook_fn.Media fun(ctx: crap.hook.Media): crap.hook.Media

---@class crap.filters.Media
---@field id? crap.FilterValue
---@field filename? crap.FilterValue
---@field mime_type? crap.FilterValue
---@field filesize? crap.FilterValue
---@field width? crap.FilterValue
---@field height? crap.FilterValue
---@field url? crap.FilterValue
---@field thumbnail_url? crap.FilterValue
---@field thumbnail_width? crap.FilterValue
---@field thumbnail_height? crap.FilterValue
---@field card_url? crap.FilterValue
---@field card_width? crap.FilterValue
---@field card_height? crap.FilterValue
---@field hero_url? crap.FilterValue
---@field hero_width? crap.FilterValue
---@field hero_height? crap.FilterValue
---@field alt? crap.FilterValue
---@field caption? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class crap.query.Media
---@field filters? crap.filters.Media
---@field order_by? "id"|"-id"|"filename"|"-filename"|"mime_type"|"-mime_type"|"filesize"|"-filesize"|"width"|"-width"|"height"|"-height"|"url"|"-url"|"thumbnail_url"|"-thumbnail_url"|"thumbnail_width"|"-thumbnail_width"|"thumbnail_height"|"-thumbnail_height"|"card_url"|"-card_url"|"card_width"|"-card_width"|"card_height"|"-card_height"|"hero_url"|"-hero_url"|"hero_width"|"-hero_width"|"hero_height"|"-hero_height"|"alt"|"-alt"|"caption"|"-caption"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.data.Pages
---@field title string
---@field slug string
---@field content? table[]
---@field seo? table

---@class crap.doc.Pages
---@field id string
---@field title string
---@field slug string
---@field content? table[]
---@field seo? table
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Pages
---@field collection "pages"
---@field operation "create" | "update"
---@field data crap.data.Pages

---@class crap.find_result.Pages
---@field documents crap.doc.Pages[]
---@field total integer

---@alias crap.hook_fn.Pages fun(ctx: crap.hook.Pages): crap.hook.Pages

---@class crap.filters.Pages
---@field id? crap.FilterValue
---@field title? crap.FilterValue
---@field slug? crap.FilterValue
---@field seo__meta_title? crap.FilterValue
---@field seo__meta_description? crap.FilterValue
---@field seo__og_image? crap.FilterValue
---@field seo__no_index? crap.FilterValue
---@field _status? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class crap.query.Pages
---@field filters? crap.filters.Pages
---@field order_by? "id"|"-id"|"title"|"-title"|"slug"|"-slug"|"seo__meta_title"|"-seo__meta_title"|"seo__meta_description"|"-seo__meta_description"|"seo__og_image"|"-seo__og_image"|"seo__no_index"|"-seo__no_index"|"_status"|"-_status"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.data.Posts
---@field title string
---@field slug string
---@field author string
---@field featured_image? string
---@field excerpt string
---@field content? table[]
---@field post_type "article" | "link" | "video"
---@field external_url? string
---@field category? string
---@field tags? string[]
---@field published_at? string
---@field seo? table

---@class crap.doc.Posts
---@field id string
---@field title string
---@field slug string
---@field author string
---@field featured_image? string
---@field excerpt string
---@field content? table[]
---@field post_type "article" | "link" | "video"
---@field external_url? string
---@field category? string
---@field tags? string[]
---@field published_at? string
---@field seo? table
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Posts
---@field collection "posts"
---@field operation "create" | "update"
---@field data crap.data.Posts

---@class crap.find_result.Posts
---@field documents crap.doc.Posts[]
---@field total integer

---@alias crap.hook_fn.Posts fun(ctx: crap.hook.Posts): crap.hook.Posts

---@class crap.filters.Posts
---@field id? crap.FilterValue
---@field title? crap.FilterValue
---@field slug? crap.FilterValue
---@field author? crap.FilterValue
---@field featured_image? crap.FilterValue
---@field excerpt? crap.FilterValue
---@field post_type? crap.FilterValue
---@field external_url? crap.FilterValue
---@field category? crap.FilterValue
---@field published_at? crap.FilterValue
---@field seo__meta_title? crap.FilterValue
---@field seo__meta_description? crap.FilterValue
---@field seo__og_image? crap.FilterValue
---@field seo__no_index? crap.FilterValue
---@field _status? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class crap.query.Posts
---@field filters? crap.filters.Posts
---@field order_by? "id"|"-id"|"title"|"-title"|"slug"|"-slug"|"author"|"-author"|"featured_image"|"-featured_image"|"excerpt"|"-excerpt"|"post_type"|"-post_type"|"external_url"|"-external_url"|"category"|"-category"|"published_at"|"-published_at"|"seo__meta_title"|"-seo__meta_title"|"seo__meta_description"|"-seo__meta_description"|"seo__og_image"|"-seo__og_image"|"seo__no_index"|"-seo__no_index"|"_status"|"-_status"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.data.Tags
---@field title string
---@field slug string
---@field seo? table

---@class crap.doc.Tags
---@field id string
---@field title string
---@field slug string
---@field seo? table
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Tags
---@field collection "tags"
---@field operation "create" | "update"
---@field data crap.data.Tags

---@class crap.find_result.Tags
---@field documents crap.doc.Tags[]
---@field total integer

---@alias crap.hook_fn.Tags fun(ctx: crap.hook.Tags): crap.hook.Tags

---@class crap.filters.Tags
---@field id? crap.FilterValue
---@field title? crap.FilterValue
---@field slug? crap.FilterValue
---@field seo__meta_title? crap.FilterValue
---@field seo__meta_description? crap.FilterValue
---@field seo__no_index? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class crap.query.Tags
---@field filters? crap.filters.Tags
---@field order_by? "id"|"-id"|"title"|"-title"|"slug"|"-slug"|"seo__meta_title"|"-seo__meta_title"|"seo__meta_description"|"-seo__meta_description"|"seo__no_index"|"-seo__no_index"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.data.Users
---@field email string
---@field name string
---@field role "admin" | "editor" | "author"
---@field avatar? string
---@field bio? string

---@class crap.doc.Users
---@field id string
---@field email string
---@field name string
---@field role "admin" | "editor" | "author"
---@field avatar? string
---@field bio? string
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Users
---@field collection "users"
---@field operation "create" | "update"
---@field data crap.data.Users

---@class crap.find_result.Users
---@field documents crap.doc.Users[]
---@field total integer

---@alias crap.hook_fn.Users fun(ctx: crap.hook.Users): crap.hook.Users

---@class crap.filters.Users
---@field id? crap.FilterValue
---@field email? crap.FilterValue
---@field name? crap.FilterValue
---@field role? crap.FilterValue
---@field avatar? crap.FilterValue
---@field bio? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class crap.query.Users
---@field filters? crap.filters.Users
---@field order_by? "id"|"-id"|"email"|"-email"|"name"|"-name"|"role"|"-role"|"avatar"|"-avatar"|"bio"|"-bio"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.global_data.SiteSettings
---@field site_name string
---@field tagline? string
---@field description? string
---@field logo? string
---@field favicon? string
---@field social? table
---@field seo? table

---@class crap.global_doc.SiteSettings
---@field id string
---@field site_name string
---@field tagline? string
---@field description? string
---@field logo? string
---@field favicon? string
---@field social? table
---@field seo? table
---@field created_at? string
---@field updated_at? string

---@class crap.hook.global_site_settings
---@field global "site_settings"
---@field operation "create" | "update"
---@field data crap.global_data.SiteSettings

---@overload fun(collection: "categories", query?: crap.query.Categories): crap.find_result.Categories
---@overload fun(collection: "media", query?: crap.query.Media): crap.find_result.Media
---@overload fun(collection: "pages", query?: crap.query.Pages): crap.find_result.Pages
---@overload fun(collection: "posts", query?: crap.query.Posts): crap.find_result.Posts
---@overload fun(collection: "tags", query?: crap.query.Tags): crap.find_result.Tags
---@overload fun(collection: "users", query?: crap.query.Users): crap.find_result.Users
---@param collection string
---@param query? crap.FindQuery
---@return crap.FindResult
function crap.collections.find(collection, query) end

