# Auto-generated by crap-cms. Do not edit.

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional, Any

@dataclass
class Articles:
    """Select fields — category: "news", "tutorial", "opinion""""
    id: str = ""
    title: str = ""
    slug: str = ""
    summary: Optional[str] = None
    body: Optional[str] = None
    category: Optional[str] = None
    author: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

@dataclass
class Media:
    id: str = ""
    filename: str = ""
    mime_type: Optional[str] = None
    filesize: Optional[float] = None
    width: Optional[float] = None
    height: Optional[float] = None
    url: Optional[str] = None
    thumbnail_url: Optional[str] = None
    thumbnail_width: Optional[float] = None
    thumbnail_height: Optional[float] = None
    thumbnail_webp_url: Optional[str] = None
    thumbnail_avif_url: Optional[str] = None
    card_url: Optional[str] = None
    card_width: Optional[float] = None
    card_height: Optional[float] = None
    card_webp_url: Optional[str] = None
    card_avif_url: Optional[str] = None
    alt: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

@dataclass
class Pages:
    id: str = ""
    title: str = ""
    slug: str = ""
    published: Optional[bool] = None
    seo: Optional[dict] = None
    hero_image: Optional[str] = None
    content: Optional[list[dict]] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

@dataclass
class PostsSlides:
    title: str = ""
    image_url: Optional[str] = None
    caption: Optional[str] = None

@dataclass
class Posts:
    """Select fields — status: "draft", "published", "archived""""
    id: str = ""
    title: str = ""
    slug: str = ""
    status: str = ""
    content: Optional[str] = None
    tags: Optional[list[str]] = None
    slides: Optional[list[dict]] = None
    featured_image: Optional[str] = None
    author: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

@dataclass
class Tags:
    id: str = ""
    name: str = ""
    color: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

@dataclass
class Users:
    """Select fields — role: "admin", "editor""""
    id: str = ""
    email: str = ""
    name: str = ""
    role: str = ""
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

@dataclass
class SiteSettings:
    id: str = ""
    site_name: str = ""
    tagline: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

