// Auto-generated by crap-cms. Do not edit.

/** Input data for creating/updating a Articles */
export interface ArticlesData {
  title: string;
  slug: string;
  summary?: string;
  body?: string;
  category?: "news" | "tutorial" | "opinion";
  author?: string;
}

/** Articles document returned from the API */
export interface ArticlesDocument extends ArticlesData {
  id: string;
  created_at?: string;
  updated_at?: string;
}

/** Input data for creating/updating a Media */
export interface MediaData {
  filename: string;
  mime_type?: string;
  filesize?: number;
  width?: number;
  height?: number;
  url?: string;
  thumbnail_url?: string;
  thumbnail_width?: number;
  thumbnail_height?: number;
  thumbnail_webp_url?: string;
  thumbnail_avif_url?: string;
  card_url?: string;
  card_width?: number;
  card_height?: number;
  card_webp_url?: string;
  card_avif_url?: string;
  alt?: string;
}

/** Media document returned from the API */
export interface MediaDocument extends MediaData {
  id: string;
  created_at?: string;
  updated_at?: string;
}

/** Input data for creating/updating a Pages */
export interface PagesData {
  title: string;
  slug: string;
  published?: boolean;
  seo?: Record<string, unknown>;
  hero_image?: string;
  content?: Record<string, unknown>[];
}

/** Pages document returned from the API */
export interface PagesDocument extends PagesData {
  id: string;
  created_at?: string;
  updated_at?: string;
}

export interface PostsSlides {
  title: string;
  image_url?: string;
  caption?: string;
}

/** Input data for creating/updating a Posts */
export interface PostsData {
  title: string;
  slug: string;
  status: "draft" | "published" | "archived";
  content?: string;
  tags?: string[];
  slides?: PostsSlides[];
  featured_image?: string;
  author?: string;
}

/** Posts document returned from the API */
export interface PostsDocument extends PostsData {
  id: string;
  created_at?: string;
  updated_at?: string;
}

/** Input data for creating/updating a Tags */
export interface TagsData {
  name: string;
  color?: string;
}

/** Tags document returned from the API */
export interface TagsDocument extends TagsData {
  id: string;
  created_at?: string;
  updated_at?: string;
}

/** Input data for creating/updating a Users */
export interface UsersData {
  email: string;
  name: string;
  role: "admin" | "editor";
}

/** Users document returned from the API */
export interface UsersDocument extends UsersData {
  id: string;
  created_at?: string;
  updated_at?: string;
}

/** Input data for SiteSettings global */
export interface SiteSettingsData {
  site_name: string;
  tagline?: string;
}

/** SiteSettings global document */
export interface SiteSettingsDocument extends SiteSettingsData {
  id: string;
  created_at?: string;
  updated_at?: string;
}

/** All collection slugs */
export type CollectionSlug = "articles" | "media" | "pages" | "posts" | "tags" | "users";
