//! Go type definition generator — structs with json tags for gRPC clients.

use std::fmt::Write;

use crate::core::collection::{CollectionDefinition, GlobalDefinition};
use crate::core::field::{FieldDefinition, FieldType};
use crate::core::Registry;

use super::{is_optional, sorted_collection_slugs, sorted_global_slugs, to_pascal_case};

pub(super) fn render(registry: &Registry) -> String {
    let mut out = String::from("// Auto-generated by crap-cms. Do not edit.\n\npackage types\n\n");

    for slug in sorted_collection_slugs(registry) {
        let col = &registry.collections[slug];
        render_collection(&mut out, col);
    }

    for slug in sorted_global_slugs(registry) {
        let global = &registry.globals[slug];
        render_global(&mut out, global);
    }

    out
}

fn render_collection(out: &mut String, col: &CollectionDefinition) {
    let pascal = to_pascal_case(&col.slug);

    // Array sub-types
    for f in &col.fields {
        if f.field_type == FieldType::Array && !f.fields.is_empty() {
            let sub_pascal = format!("{}{}", pascal, to_pascal_case(&f.name));
            writeln!(out, "// {} represents a row in the {} array field.", sub_pascal, f.name).unwrap();
            writeln!(out, "type {} struct {{", sub_pascal).unwrap();
            for sf in &f.fields {
                write_field(out, sf);
            }
            writeln!(out, "}}\n").unwrap();
        }
    }

    // Document struct (includes id, fields, and timestamps)
    writeln!(out, "// {} represents a {} document.", pascal, col.slug).unwrap();
    writeln!(out, "type {} struct {{", pascal).unwrap();
    writeln!(out, "\tID        string  `json:\"id\"`").unwrap();
    for f in &col.fields {
        write_field_with_context(out, f, &pascal);
    }
    if col.timestamps {
        writeln!(out, "\tCreatedAt *string `json:\"created_at,omitempty\"`").unwrap();
        writeln!(out, "\tUpdatedAt *string `json:\"updated_at,omitempty\"`").unwrap();
    }
    writeln!(out, "}}\n").unwrap();
}

fn render_global(out: &mut String, global: &GlobalDefinition) {
    let pascal = to_pascal_case(&global.slug);

    writeln!(out, "// {} represents the {} global.", pascal, global.slug).unwrap();
    writeln!(out, "type {} struct {{", pascal).unwrap();
    writeln!(out, "\tID        string  `json:\"id\"`").unwrap();
    for f in &global.fields {
        write_field(out, f);
    }
    writeln!(out, "\tCreatedAt *string `json:\"created_at,omitempty\"`").unwrap();
    writeln!(out, "\tUpdatedAt *string `json:\"updated_at,omitempty\"`").unwrap();
    writeln!(out, "}}\n").unwrap();
}

fn write_field(out: &mut String, field: &FieldDefinition) {
    write_field_with_context(out, field, "");
}

fn write_field_with_context(out: &mut String, field: &FieldDefinition, parent_pascal: &str) {
    let go_name = to_pascal_case(&field.name);
    let (go_type, omitempty) = field_to_go(field, parent_pascal);
    let tag = if omitempty {
        format!("`json:\"{},omitempty\"`", field.name)
    } else {
        format!("`json:\"{}\"`", field.name)
    };
    writeln!(out, "\t{:<9} {} {}", go_name, go_type, tag).unwrap();
}

fn field_to_go(field: &FieldDefinition, parent_pascal: &str) -> (String, bool) {
    let optional = is_optional(field);
    match &field.field_type {
        FieldType::Text | FieldType::Textarea | FieldType::Email | FieldType::Date
        | FieldType::Richtext | FieldType::Select => {
            if optional {
                ("*string".to_string(), true)
            } else {
                ("string".to_string(), false)
            }
        }
        FieldType::Number => {
            if optional {
                ("*float64".to_string(), true)
            } else {
                ("float64".to_string(), false)
            }
        }
        FieldType::Checkbox => ("bool".to_string(), true),
        FieldType::Json => ("interface{}".to_string(), true),
        FieldType::Relationship => {
            match &field.relationship {
                Some(rc) if rc.has_many => ("[]string".to_string(), true),
                _ if optional => ("*string".to_string(), true),
                _ => ("string".to_string(), false),
            }
        }
        FieldType::Array => {
            if field.fields.is_empty() {
                ("[]map[string]interface{}".to_string(), true)
            } else {
                let sub = format!("[]{}{}",  parent_pascal, to_pascal_case(&field.name));
                (sub, true)
            }
        }
        FieldType::Group => ("map[string]interface{}".to_string(), true),
        FieldType::Upload => {
            if optional {
                ("*string".to_string(), true)
            } else {
                ("string".to_string(), false)
            }
        }
        FieldType::Blocks => ("[]map[string]interface{}".to_string(), true),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::collection::{
        CollectionAccess, CollectionAdmin, CollectionHooks, CollectionLabels,
    };
    use crate::core::field::{FieldAccess, FieldAdmin, FieldHooks};

    fn text_field(name: &str, required: bool) -> FieldDefinition {
        FieldDefinition {
            name: name.to_string(), field_type: FieldType::Text, required,
            unique: false, validate: None, default_value: None, options: vec![],
            admin: FieldAdmin::default(), hooks: FieldHooks::default(),
            access: FieldAccess::default(), relationship: None,
            fields: vec![], blocks: vec![], localized: false, picker_appearance: None,
        }
    }

    #[test]
    fn go_collection_output() {
        let col = CollectionDefinition {
            slug: "posts".to_string(), labels: CollectionLabels::default(),
            timestamps: true,
            fields: vec![text_field("title", true), text_field("content", false)],
            admin: CollectionAdmin::default(), hooks: CollectionHooks::default(),
            auth: None, upload: None, access: CollectionAccess::default(),
            live: None, versions: None,
        };

        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(out.contains("type Posts struct {"));
        assert!(out.contains("ID        string  `json:\"id\"`"));
        assert!(out.contains("Title     string `json:\"title\"`"));
        assert!(out.contains("Content   *string `json:\"content,omitempty\"`"));
        assert!(out.contains("CreatedAt *string `json:\"created_at,omitempty\"`"));
    }
}
