//! Python type definition generator — dataclasses for gRPC clients.

use std::fmt::Write;

use crate::core::collection::{CollectionDefinition, GlobalDefinition};
use crate::core::field::{FieldDefinition, FieldType};
use crate::core::Registry;

use super::{is_optional, sorted_collection_slugs, sorted_global_slugs, to_pascal_case};

pub(super) fn render(registry: &Registry) -> String {
    let mut out = String::new();
    writeln!(out, "# Auto-generated by crap-cms. Do not edit.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "from __future__ import annotations").unwrap();
    writeln!(out, "from dataclasses import dataclass, field").unwrap();
    writeln!(out, "from typing import Optional, Any\n").unwrap();

    for slug in sorted_collection_slugs(registry) {
        let col = &registry.collections[slug];
        render_collection(&mut out, col);
    }

    for slug in sorted_global_slugs(registry) {
        let global = &registry.globals[slug];
        render_global(&mut out, global);
    }

    out
}

fn render_collection(out: &mut String, col: &CollectionDefinition) {
    let pascal = to_pascal_case(&col.slug);

    // Array sub-types
    for f in &col.fields {
        if f.field_type == FieldType::Array && !f.fields.is_empty() {
            let sub_pascal = format!("{}{}", pascal, to_pascal_case(&f.name));
            writeln!(out, "@dataclass").unwrap();
            writeln!(out, "class {}:", sub_pascal).unwrap();
            let (required, optional): (Vec<_>, Vec<_>) = f.fields.iter()
                .partition(|sf| !is_optional(sf));
            for sf in &required {
                write_field(out, sf);
            }
            for sf in &optional {
                write_field(out, sf);
            }
            if f.fields.is_empty() {
                writeln!(out, "    pass").unwrap();
            }
            writeln!(out).unwrap();
        }
    }

    // Document class (required fields first, then optional with defaults)
    let comment = field_options_comment(col);
    writeln!(out, "@dataclass").unwrap();
    writeln!(out, "class {}:", pascal).unwrap();
    if !comment.is_empty() {
        writeln!(out, "    \"\"\"{}\"\"\"", comment).unwrap();
    }
    // id first (always required)
    writeln!(out, "    id: str = \"\"").unwrap();

    // Required fields first
    for f in &col.fields {
        if !is_optional(f) {
            write_field(out, f);
        }
    }
    // Optional fields
    for f in &col.fields {
        if is_optional(f) {
            write_field(out, f);
        }
    }
    if col.timestamps {
        writeln!(out, "    created_at: Optional[str] = None").unwrap();
        writeln!(out, "    updated_at: Optional[str] = None").unwrap();
    }
    writeln!(out).unwrap();
}

fn render_global(out: &mut String, global: &GlobalDefinition) {
    let pascal = to_pascal_case(&global.slug);

    writeln!(out, "@dataclass").unwrap();
    writeln!(out, "class {}:", pascal).unwrap();
    writeln!(out, "    id: str = \"\"").unwrap();

    for f in &global.fields {
        if !is_optional(f) {
            write_field(out, f);
        }
    }
    for f in &global.fields {
        if is_optional(f) {
            write_field(out, f);
        }
    }
    writeln!(out, "    created_at: Optional[str] = None").unwrap();
    writeln!(out, "    updated_at: Optional[str] = None").unwrap();
    writeln!(out).unwrap();
}

fn write_field(out: &mut String, field: &FieldDefinition) {
    let py_type = field_to_py(field);
    if is_optional(field) {
        writeln!(out, "    {}: Optional[{}] = None", field.name, py_type).unwrap();
    } else {
        let default = default_for_type(field);
        writeln!(out, "    {}: {} = {}", field.name, py_type, default).unwrap();
    }
}

fn field_to_py(field: &FieldDefinition) -> String {
    match &field.field_type {
        FieldType::Text | FieldType::Textarea | FieldType::Email | FieldType::Date
        | FieldType::Richtext | FieldType::Select | FieldType::Upload => "str".to_string(),
        FieldType::Number => "float".to_string(),
        FieldType::Checkbox => "bool".to_string(),
        FieldType::Json => "Any".to_string(),
        FieldType::Relationship => {
            match &field.relationship {
                Some(rc) if rc.has_many => "list[str]".to_string(),
                _ => "str".to_string(),
            }
        }
        FieldType::Array => "list[dict]".to_string(),
        FieldType::Group => "dict".to_string(),
        FieldType::Blocks => "list[dict]".to_string(),
    }
}

fn default_for_type(field: &FieldDefinition) -> &'static str {
    match &field.field_type {
        FieldType::Number => "0.0",
        FieldType::Checkbox => "False",
        _ => "\"\"",
    }
}

/// Generate a docstring comment listing select field options.
fn field_options_comment(col: &CollectionDefinition) -> String {
    let selects: Vec<String> = col.fields.iter()
        .filter(|f| f.field_type == FieldType::Select && !f.options.is_empty())
        .map(|f| {
            let opts = f.options.iter().map(|o| format!("\"{}\"", o.value)).collect::<Vec<_>>().join(", ");
            format!("{}: {}", f.name, opts)
        })
        .collect();
    if selects.is_empty() {
        String::new()
    } else {
        format!("Select fields — {}", selects.join("; "))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::collection::{
        CollectionAccess, CollectionAdmin, CollectionHooks, CollectionLabels,
    };

    fn text_field(name: &str, required: bool) -> FieldDefinition {
        FieldDefinition {
            name: name.to_string(),
            required,
            ..Default::default()
        }
    }

    #[test]
    fn python_collection_output() {
        let col = CollectionDefinition {
            slug: "posts".to_string(), labels: CollectionLabels::default(),
            timestamps: true,
            fields: vec![text_field("title", true), text_field("content", false)],
            admin: CollectionAdmin::default(), hooks: CollectionHooks::default(),
            auth: None, upload: None, access: CollectionAccess::default(),
            live: None, versions: None,
        };

        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(out.contains("@dataclass"));
        assert!(out.contains("class Posts:"));
        assert!(out.contains("    id: str = \"\""));
        assert!(out.contains("    title: str = \"\""));
        assert!(out.contains("    content: Optional[str] = None"));
        assert!(out.contains("    created_at: Optional[str] = None"));
    }
}
