//! Rust type definition generator — structs with serde derives for gRPC clients.

use std::fmt::Write;

use crate::core::collection::{CollectionDefinition, GlobalDefinition};
use crate::core::field::{FieldDefinition, FieldType};
use crate::core::Registry;

use super::{is_optional, sorted_collection_slugs, sorted_global_slugs, to_pascal_case};

pub(super) fn render(registry: &Registry) -> String {
    let mut out = String::new();
    writeln!(out, "// Auto-generated by crap-cms. Do not edit.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use serde::{{Deserialize, Serialize}};\n").unwrap();

    for slug in sorted_collection_slugs(registry) {
        let col = &registry.collections[slug];
        render_collection(&mut out, col);
    }

    for slug in sorted_global_slugs(registry) {
        let global = &registry.globals[slug];
        render_global(&mut out, global);
    }

    out
}

fn render_collection(out: &mut String, col: &CollectionDefinition) {
    let pascal = to_pascal_case(&col.slug);

    // Array sub-types
    for f in &col.fields {
        if f.field_type == FieldType::Array && !f.fields.is_empty() {
            let sub_pascal = format!("{}{}", pascal, to_pascal_case(&f.name));
            writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
            writeln!(out, "pub struct {} {{", sub_pascal).unwrap();
            for sf in &f.fields {
                write_field(out, sf);
            }
            writeln!(out, "}}\n").unwrap();
        }
    }

    // Document struct
    writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
    writeln!(out, "pub struct {} {{", pascal).unwrap();
    writeln!(out, "    pub id: String,").unwrap();
    for f in &col.fields {
        write_field_with_context(out, f, &pascal);
    }
    if col.timestamps {
        writeln!(out, "    #[serde(skip_serializing_if = \"Option::is_none\")]").unwrap();
        writeln!(out, "    pub created_at: Option<String>,").unwrap();
        writeln!(out, "    #[serde(skip_serializing_if = \"Option::is_none\")]").unwrap();
        writeln!(out, "    pub updated_at: Option<String>,").unwrap();
    }
    writeln!(out, "}}\n").unwrap();
}

fn render_global(out: &mut String, global: &GlobalDefinition) {
    let pascal = to_pascal_case(&global.slug);

    writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
    writeln!(out, "pub struct {} {{", pascal).unwrap();
    writeln!(out, "    pub id: String,").unwrap();
    for f in &global.fields {
        write_field(out, f);
    }
    writeln!(out, "    #[serde(skip_serializing_if = \"Option::is_none\")]").unwrap();
    writeln!(out, "    pub created_at: Option<String>,").unwrap();
    writeln!(out, "    #[serde(skip_serializing_if = \"Option::is_none\")]").unwrap();
    writeln!(out, "    pub updated_at: Option<String>,").unwrap();
    writeln!(out, "}}\n").unwrap();
}

fn write_field(out: &mut String, field: &FieldDefinition) {
    write_field_with_context(out, field, "");
}

fn write_field_with_context(out: &mut String, field: &FieldDefinition, parent_pascal: &str) {
    let rust_type = field_to_rust(field, parent_pascal);
    if is_optional(field) {
        writeln!(out, "    #[serde(skip_serializing_if = \"Option::is_none\")]").unwrap();
        writeln!(out, "    pub {}: Option<{}>,", field.name, rust_type).unwrap();
    } else {
        writeln!(out, "    pub {}: {},", field.name, rust_type).unwrap();
    }
}

fn field_to_rust(field: &FieldDefinition, parent_pascal: &str) -> String {
    match &field.field_type {
        FieldType::Text | FieldType::Textarea | FieldType::Email | FieldType::Date
        | FieldType::Richtext | FieldType::Select | FieldType::Upload => "String".to_string(),
        FieldType::Number => "f64".to_string(),
        FieldType::Checkbox => "bool".to_string(),
        FieldType::Json => "serde_json::Value".to_string(),
        FieldType::Relationship => {
            match &field.relationship {
                Some(rc) if rc.has_many => "Vec<String>".to_string(),
                _ => "String".to_string(),
            }
        }
        FieldType::Array => {
            if field.fields.is_empty() {
                "Vec<serde_json::Value>".to_string()
            } else {
                format!("Vec<{}{}>", parent_pascal, to_pascal_case(&field.name))
            }
        }
        FieldType::Group => "serde_json::Value".to_string(),
        FieldType::Blocks => "Vec<serde_json::Value>".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::collection::{
        CollectionAccess, CollectionAdmin, CollectionHooks, CollectionLabels,
    };

    fn text_field(name: &str, required: bool) -> FieldDefinition {
        FieldDefinition {
            name: name.to_string(),
            required,
            ..Default::default()
        }
    }

    #[test]
    fn rust_collection_output() {
        let col = CollectionDefinition {
            slug: "posts".to_string(), labels: CollectionLabels::default(),
            timestamps: true,
            fields: vec![text_field("title", true), text_field("content", false)],
            admin: CollectionAdmin::default(), hooks: CollectionHooks::default(),
            auth: None, upload: None, access: CollectionAccess::default(),
            live: None, versions: None,
        };

        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(out.contains("#[derive(Debug, Clone, Serialize, Deserialize)]"));
        assert!(out.contains("pub struct Posts {"));
        assert!(out.contains("    pub id: String,"));
        assert!(out.contains("    pub title: String,"));
        assert!(out.contains("    pub content: Option<String>,"));
        assert!(out.contains("    pub created_at: Option<String>,"));
    }
}
