//! TypeScript type definition generator — interfaces for gRPC client wrappers.

use std::fmt::Write;

use crate::core::collection::{CollectionDefinition, GlobalDefinition};
use crate::core::field::{FieldDefinition, FieldType};
use crate::core::Registry;

use super::{is_optional, sorted_collection_slugs, sorted_global_slugs, to_pascal_case};

pub(super) fn render(registry: &Registry) -> String {
    let mut out = String::from("// Auto-generated by crap-cms. Do not edit.\n\n");

    for slug in sorted_collection_slugs(registry) {
        let col = &registry.collections[slug];
        render_collection(&mut out, col);
    }

    for slug in sorted_global_slugs(registry) {
        let global = &registry.globals[slug];
        render_global(&mut out, global);
    }

    render_collection_slug_type(&mut out, registry);

    out
}

fn render_collection(out: &mut String, col: &CollectionDefinition) {
    let pascal = to_pascal_case(&col.slug);

    // Array sub-types
    for f in &col.fields {
        if f.field_type == FieldType::Array && !f.fields.is_empty() {
            let sub_pascal = format!("{}{}", pascal, to_pascal_case(&f.name));
            writeln!(out, "export interface {} {{", sub_pascal).unwrap();
            for sf in &f.fields {
                write_field(out, sf);
            }
            writeln!(out, "}}\n").unwrap();
        }
    }

    // Input data interface
    writeln!(out, "/** Input data for creating/updating a {} */", pascal).unwrap();
    writeln!(out, "export interface {}Data {{", pascal).unwrap();
    for f in &col.fields {
        write_field_with_context(out, f, &pascal);
    }
    writeln!(out, "}}\n").unwrap();

    // Document interface (extends data with id + timestamps)
    writeln!(out, "/** {} document returned from the API */", pascal).unwrap();
    writeln!(out, "export interface {}Document extends {}Data {{", pascal, pascal).unwrap();
    writeln!(out, "  id: string;").unwrap();
    if col.timestamps {
        writeln!(out, "  created_at?: string;").unwrap();
        writeln!(out, "  updated_at?: string;").unwrap();
    }
    writeln!(out, "}}\n").unwrap();
}

fn render_global(out: &mut String, global: &GlobalDefinition) {
    let pascal = to_pascal_case(&global.slug);

    writeln!(out, "/** Input data for {} global */", pascal).unwrap();
    writeln!(out, "export interface {}Data {{", pascal).unwrap();
    for f in &global.fields {
        write_field(out, f);
    }
    writeln!(out, "}}\n").unwrap();

    writeln!(out, "/** {} global document */", pascal).unwrap();
    writeln!(out, "export interface {}Document extends {}Data {{", pascal, pascal).unwrap();
    writeln!(out, "  id: string;").unwrap();
    writeln!(out, "  created_at?: string;").unwrap();
    writeln!(out, "  updated_at?: string;").unwrap();
    writeln!(out, "}}\n").unwrap();
}

fn render_collection_slug_type(out: &mut String, registry: &Registry) {
    let slugs = sorted_collection_slugs(registry);
    if slugs.is_empty() {
        return;
    }
    let union = slugs.iter().map(|s| format!("\"{}\"", s)).collect::<Vec<_>>().join(" | ");
    writeln!(out, "/** All collection slugs */").unwrap();
    writeln!(out, "export type CollectionSlug = {};", union).unwrap();
}

fn write_field(out: &mut String, field: &FieldDefinition) {
    let ts_type = field_to_ts(field, "");
    let opt = if is_optional(field) { "?" } else { "" };
    writeln!(out, "  {}{}: {};", field.name, opt, ts_type).unwrap();
}

fn write_field_with_context(out: &mut String, field: &FieldDefinition, parent_pascal: &str) {
    let ts_type = field_to_ts(field, parent_pascal);
    let opt = if is_optional(field) { "?" } else { "" };
    writeln!(out, "  {}{}: {};", field.name, opt, ts_type).unwrap();
}

fn field_to_ts(field: &FieldDefinition, parent_pascal: &str) -> String {
    match &field.field_type {
        FieldType::Text | FieldType::Textarea | FieldType::Email | FieldType::Date
        | FieldType::Richtext => "string".to_string(),
        FieldType::Number => "number".to_string(),
        FieldType::Checkbox => "boolean".to_string(),
        FieldType::Json => "unknown".to_string(),
        FieldType::Select => {
            if field.options.is_empty() {
                "string".to_string()
            } else {
                field.options.iter()
                    .map(|o| format!("\"{}\"", o.value))
                    .collect::<Vec<_>>()
                    .join(" | ")
            }
        }
        FieldType::Relationship => {
            match &field.relationship {
                Some(rc) if rc.has_many => "string[]".to_string(),
                _ => "string".to_string(),
            }
        }
        FieldType::Array => {
            if field.fields.is_empty() {
                "Record<string, unknown>[]".to_string()
            } else {
                format!("{}{}[]", parent_pascal, to_pascal_case(&field.name))
            }
        }
        FieldType::Group => "Record<string, unknown>".to_string(),
        FieldType::Upload => "string".to_string(),
        FieldType::Blocks => "Record<string, unknown>[]".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::collection::{
        CollectionAccess, CollectionAdmin, CollectionHooks, CollectionLabels,
    };
    use crate::core::field::{FieldAccess, FieldAdmin, FieldHooks, LocalizedString, SelectOption};

    fn text_field(name: &str, required: bool) -> FieldDefinition {
        FieldDefinition {
            name: name.to_string(), field_type: FieldType::Text, required,
            unique: false, validate: None, default_value: None, options: vec![],
            admin: FieldAdmin::default(), hooks: FieldHooks::default(),
            access: FieldAccess::default(), relationship: None,
            fields: vec![], blocks: vec![], localized: false, picker_appearance: None,
        }
    }

    fn select_field(name: &str, opts: &[&str]) -> FieldDefinition {
        FieldDefinition {
            name: name.to_string(), field_type: FieldType::Select, required: true,
            unique: false, validate: None, default_value: None,
            options: opts.iter().map(|v| SelectOption {
                label: LocalizedString::Plain(v.to_string()), value: v.to_string(),
            }).collect(),
            admin: FieldAdmin::default(), hooks: FieldHooks::default(),
            access: FieldAccess::default(), relationship: None,
            fields: vec![], blocks: vec![], localized: false, picker_appearance: None,
        }
    }

    #[test]
    fn typescript_collection_output() {
        let col = CollectionDefinition {
            slug: "posts".to_string(), labels: CollectionLabels::default(),
            timestamps: true,
            fields: vec![
                text_field("title", true),
                text_field("content", false),
                select_field("status", &["draft", "published"]),
            ],
            admin: CollectionAdmin::default(), hooks: CollectionHooks::default(),
            auth: None, upload: None, access: CollectionAccess::default(),
            live: None, versions: None,
        };

        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(out.contains("export interface PostsData {"));
        assert!(out.contains("  title: string;"));
        assert!(out.contains("  content?: string;"));
        assert!(out.contains("  status: \"draft\" | \"published\";"));
        assert!(out.contains("export interface PostsDocument extends PostsData {"));
        assert!(out.contains("  id: string;"));
        assert!(out.contains("  created_at?: string;"));
        assert!(out.contains("  updated_at?: string;"));
    }

    #[test]
    fn typescript_global_output() {
        let global = GlobalDefinition {
            slug: "site_settings".to_string(), labels: CollectionLabels::default(),
            fields: vec![text_field("site_name", true)],
            hooks: CollectionHooks::default(), access: CollectionAccess::default(),
            live: None,
        };

        let mut out = String::new();
        render_global(&mut out, &global);

        assert!(out.contains("export interface SiteSettingsData {"));
        assert!(out.contains("export interface SiteSettingsDocument extends SiteSettingsData {"));
    }
}
